// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Qc6U7BMt9E_OI9-0290nb4lhCsfPpxk',
    appId: '1:662653589615:web:18215db55f43dbe17a159a',
    messagingSenderId: '662653589615',
    projectId: 'better-world-60db9',
    authDomain: 'better-world-60db9.firebaseapp.com',
    storageBucket: 'better-world-60db9.firebasestorage.app',
    measurementId: 'G-XPPP2J0QQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG66COVZNJksNKWiUune0LTbBauPQyv1w',
    appId: '1:662653589615:android:6738bc9f11188f917a159a',
    messagingSenderId: '662653589615',
    projectId: 'better-world-60db9',
    storageBucket: 'better-world-60db9.firebasestorage.app',
  );
}
